"""Generate screenshots for Ember IDE website."""
import os
import sys
import tempfile
from pathlib import Path

os.environ["QT_QPA_PLATFORM"] = "offscreen"

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from PyQt5.QtWidgets import QApplication

from app.main_window import MainWindow, FlamePreviewDialog
from app.theme.dark_theme import apply_dark_theme


def generate():
    app = QApplication(sys.argv)
    apply_dark_theme(app)

    img_dir = ROOT / "website" / "assets" / "images"
    img_dir.mkdir(parents=True, exist_ok=True)

    # Prepare temporary workspace
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)

        flame_file = tmp_path / "app.flame"
        flame_file.write_text(
            "// Flame AI Multi-Language Spec\n"
            "@target zig\n"
            "pub fn main() !void {\n"
            '    const std = @import("std");\n'
            '    std.debug.print("Hello Ember IDE from Zig!\\n", .{});\n'
            "}\n\n"
            "@target rust\n"
            "fn main() {\n"
            '    println!("Hello Ember IDE from Rust!");\n'
            "}\n",
            encoding="utf-8",
        )

        py_file = tmp_path / "main.py"
        py_file.write_text(
            'from app.main_window import MainWindow\n\nif __name__ == "__main__":\n    print("Ember IDE Engine Running...")\n',
            encoding="utf-8",
        )

        w = MainWindow()
        w.resize(1360, 860)
        w.explorer.set_root(tmp_path)
        w.editor.open_file(flame_file)

        # Set up terminal content
        tw = w.terminal_panel.current_widget()
        if tw:
            tw._append_plain(
                "ember-ide/workspace $ ",
                spans=[("ember-ide/workspace $ ", "#4ec9b0"), ("flame-cli build app.flame --target zig\n", "#d4d4d4")],
            )
            tw._append_plain(
                "[Flame AI] Compiling app.flame...\n"
                "[Flame AI] Target dynamic resolution: Zig (.zig)\n"
                "[Flame AI] Conversion successful! Created build/app.zig (0.042s)\n"
                "ember-ide/workspace $ ",
                spans=[
                    ("[Flame AI] ", "#ce9178"),
                    ("Compiling app.flame...\n", "#d4d4d4"),
                    ("[Flame AI] ", "#ce9178"),
                    ("Target dynamic resolution: Zig (.zig)\n", "#4ec9b0"),
                    ("[Flame AI] ", "#ce9178"),
                    ("Conversion successful! Created build/app.zig (0.042s)\n", "#6a9955"),
                    ("ember-ide/workspace $ ", "#4ec9b0"),
                ],
            )

        w.show()
        app.processEvents()

        # Capture Main IDE screenshot
        pix = w.grab()
        pix.save(str(img_dir / "ember_ide_main.png"))
        print("Saved ember_ide_main.png")

        # Capture Terminal screenshot focus
        term_pix = w.terminal_panel.grab()
        term_pix.save(str(img_dir / "ember_ide_terminal.png"))
        print("Saved ember_ide_terminal.png")

        # Capture Explorer screenshot focus
        exp_pix = w.explorer.grab()
        exp_pix.save(str(img_dir / "ember_ide_explorer.png"))
        print("Saved ember_ide_explorer.png")

        # Capture Flame AI Dialog
        dialog = FlamePreviewDialog(
            parent=w,
            filename="app.flame",
            detected_lang="zig",
            initial_code=(
                '// Generated by Flame AI Conversion Engine for Zig\n'
                'const std = @import("std");\n\n'
                'pub fn main() !void {\n'
                '    const stdout = std.io.getStdOut().writer();\n'
                '    try stdout.print("Ember IDE dynamic conversion successful!\\n", .{});\n'
                '}\n'
            ),
            default_export_path=tmp_path / "app.zig",
        )
        dialog.resize(960, 640)
        dialog.show()
        app.processEvents()

        dlg_pix = dialog.grab()
        dlg_pix.save(str(img_dir / "ember_ide_flame.png"))
        print("Saved ember_ide_flame.png")
        dialog.close()

    sys.stdout.flush()
    os._exit(0)


if __name__ == "__main__":
    generate()
